apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  namespace: nagp-assignment
spec:
  replicas: 4

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: employee-api

  template:
    metadata:
      labels:
        app: employee-api

    spec:
      containers:
      - name: employee-api
        image: saurabhjain374/employee-api:v2
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: ConnectionStrings__Default
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: CONNECTION_STRING

        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"