apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nagp-assignment
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  CONNECTION_STRING: "Host=postgres-service;Port=5432;Database=employee_db;Username=postgres;Password=postgres123"